fluent/fluent-bit-infra

.github/workflows/main.yml
.github/workflows/pr.yml
terraform/config.tf
terraform/default.auto.tfvars
terraform/domains.tf
terraform/github.tf
terraform/vars.tf

* Add github branch rules for:
* Dismiss stale PR(s)
* Enforce code reviewer +1
* Required +1 before merging
Signed-off-by: Jorge Niedbalski <jnr@metaklass.org>

workflows: enforce github branch rules

---

terraform/config.tf
terraform/github.tf

Signed-off-by: Jorge Niedbalski <jnr@metaklass.org>

add organization to provider (gh)

---

terraform/machines.tf

* Create a new machine spec for 3398

add new machine for testing 3398

---

.github/workflows/pr.yml
terraform/github.tf
terraform/machines.tf
terraform/vars.tf

* Enforce repo rules to admins
* Enforce status checks for unit/commits.
Signed-off-by: Jorge Niedbalski <jnr@metaklass.org>

github: enforce repository rules to admins.

---

.github/workflows/pr-tfsec

Added an action to run `tfsec` from Aqua on the Terraform: https://github.com/aquasecurity/tfsec
There are a few issues we should review and either ignore or update:
```
$ docker run --rm -it -v "$(pwd):/src" aquasec/tfsec /src
...
results
------------------------------------------
critical             2
high                 4
medium               2
low                  5
ignored              0
```

workflows: add Terraform security scan

---

.github/workflows/pr-tfsec.yml

Updated to fix the version of tfsec action as the latest seems to have issues currently.
Separately it requires a PR to work with so on manual dispatch we run the container directly.

Tfsec updates

---

terraform/github.tf

Resolves: https://github.com/calyptia/fluent-bit-infra/runs/4553667093?check_suite_focus=true#step:15:213

terraform: resolve misconfiguration issue

---

terraform/github.tf

terraform: fix missed policy

---

.github/workflows/call-common.yaml
.github/workflows/main.yml
.github/workflows/pr.yml
terraform/config.tf
terraform/default.auto.tfvars
terraform/domains.tf
terraform/machines.tf
terraform/vars.tf

Have to keep the original provider info until we apply on main. 
See plan here: https://github.com/calyptia/fluent-bit-infra/runs/4609188218?check_suite_focus=true

terraform: switch to metal provider

---

terraform/config.tf

terraform: remove packet post-migration

---

terraform/domains.tf
terraform/machines.tf
terraform/provision/github-runner.create.sh
terraform/provision/github-runner.destroy.sh
terraform/provision/user-data.sh
terraform/vars.tf

terraform: add new metal devices

---

terraform/machines.tf

terraform: update machines to be valid for metro

---

terraform/domains.tf
terraform/machines.tf

terraform: use tags instead

---

terraform/machines.tf
terraform/provision/github-runner.create.sh

terraform: add ubuntu labels

---

terraform/vars.tf

terraform: add Pat to approvers

---

terraform/machines.tf
terraform/provision/github-runner.create.sh
terraform/provision/github-runner.destroy.sh
terraform/provision/user-data.sh

Updated to use SSH keys and other Ubuntu fixes.
Tested on local instance.

terraform: generate key for runners

---

terraform/provision/github-runner.create.sh
terraform/provision/github-runner.destroy.sh
terraform/provision/user-data.sh

terraform: forward logs for provisioning to log & console

---

terraform/machines.tf
terraform/provision/github-runner.create.sh
terraform/provision/github-runner.destroy.sh

terraform: remove owner refs

---

terraform/provision/user-data.sh

terraform: add docker

---

terraform/provision/github-runner.create.sh

github-runners: patch in lock timeout

---

terraform/machines.tf
terraform/provision/github-runner.create.sh

Resolves https://github.com/fluent/fluent-bit/issues/4576

github-runners: remove ubuntu labels

---

terraform/provision/github-runner.create.sh
terraform/provision/github-runner.destroy.sh

github-runners: ensure destroy always completes

---

terraform/machines.tf

terraform: ignore failures on destroy due to missing resource

---

terraform/github.tf
terraform/machines.tf

Simple refactor to add the private mirror using a for-each loop so we get the same settings on both for secrets and branches.

terraform: add github mirror

---

terraform/github.tf
terraform/machines.tf

Disable of mirror repo as issues with credentials: https://github.com/calyptia/fluent-bit-infra/runs/4853166013?check_suite_focus=true#step:16:780
This just comments it all out for now so we can run the Terraform to completion with the new for-each loop.

terraform: revert GPG sign and add new default branch for mirror

---

.github/actionlint-matcher.json
.github/dependabot.yml

workflows: add dependabot

---

.github/actions/terraform-setup/action.yml

workflows: fix release bucket default

---

terraform/github.tf
terraform/machines.tf

Importing of the private repository seems to have issues so just using a data variable for now.

terraform: use data variable for mirror

---

terraform/github.tf

To test staging we need un-protected branch support

terraform: remove staging protection

---

terraform/domains.tf

domains: redirect test.fluentbit.io to netlify

domains: redirect test.fluentbit.io to netlify

---

terraform/domains.tf

domains: cname fluentbit.io/www.fluentbit.io to netlify

domains: cname fluentbit.io/www.fluentbit.io to netlify

---

terraform/domains.tf
terraform/urls.tf

terraform: update proxy URL

---

terraform/domains.tf
terraform/urls.tf

legacy: add redirect for old server

---

terraform/urls.tf

terraform: remove redirect

---

terraform/domains.tf

terraform: add CNAME for legacy server

---

terraform/domains.tf

Adds a CNAME entry for registry.fluentbit.io pointing to gateway.scarf.sh

domains: add registry.fluentbit.io pointing to gateway.scarf.sh

---

.github/actions/terraform-setup/action.yml

Signed-off-by: Jorge Niedbalski <j@calyptia.com>

replace default aws s3 bucket releases to packages.fluentbit.io

---

terraform/domains.tf

terraform: add cr domain

---

.tfsec/config.yml
terraform/github.tf

Addresses https://github.com/fluent/fluent-bit/discussions/5160 and https://github.com/fluent/fluent-bit/issues/5259

terraform: add release notification repo

---

terraform/github.tf

terraform: ensure we include org in unstable releases repo name

---

terraform/github.tf

Signed-off-by: Jorge Niedbalski <j@calyptia.com>

rename calyptia/fluent-bit-ci to fluent/fluent-bit-ci

---

terraform/github.tf
terraform/vars.tf

Support the Sandbox by detaining and managing all config - cc @agup006 

terraform: add sandbox repo

---

.github/workflows/terraform.yaml
terraform/urls.tf

terraform: reduce noise and other improvements

---

.github/actions/terraform-setup/action.yml
.github/workflows/terraform.yaml
terraform/github.tf
terraform/vars.tf

terraform: add Azure creds

---

terraform/github.tf
terraform/vars.tf

terraform: branch protection for 1.8 & 1.9

---

terraform/config.tf
terraform/vars.tf

terraform: fix Cloudflare usage for latest

---

terraform/machines.tf

machine: switch to basic auth

---

terraform/machines.tf
terraform/provision/package-server-provision.sh

machines: switch to file for user-data

---

terraform/provision/package-server-provision.sh.tftpl

Fixes niggles with metrics collection.

machines: fix metric handling for packages server

---

terraform/machines.tf
terraform/provision/package-server-provision.sh.tftpl

Automatically get certs and install them.
For now we are using `-next` subdomains to prevent any conflicts with the existing ones.

packages server: certbot configuration

---

terraform/domains.tf
terraform/machines.tf
terraform/provision/package-server-provision.sh.tftpl
terraform/vars.tf

The default bucket was changed in the action so updated this everywhere.

machines: update bucket used for releases

---

terraform/domains.tf
terraform/github.tf
terraform/provision/package-server-provision.sh.tftpl

urls: add releases mirror to bucket

---

terraform/domains.tf
terraform/machines.tf

Switch over to the new domains.
Create a new `-next` machine and set of domains for it.

terraform: update official domains for new server

---

terraform/github.tf

github: add 2.0 branch protection

---

terraform/vars.tf

adds celalettin1286 as a release approver

release-approvers: add celalettin1286
